const testData = {
    valid: {
        personIds: [
            16228,
            15,
            157,
        ],
        appearances: [{
            id: 1273,
            character: 'Casey Jones (voice)',
            original_title: 'TMNT',
            overview: 'After the defeat of their old arch nemesis, The Shredder, the Turtles have grown apart as a family. Struggling to keep them together, their rat sensei, Splinter, becomes worried when strange things begin to brew in New York City.',
            vote_count: 595,
            video: false,
            media_type: 'movie',
            poster_path: '/4hGzZ2DAjdu6IjHT7dGfiVatHEu.jpg',
            backdrop_path: '/cTjQ1Lqipf3wLnWUHogqHQFIdb9.jpg',
            popularity: 12.868,
            title: 'TMNT',
            original_language: 'en',
            genre_ids: [
                12,
                16,
                35,
                10751,
            ],
            vote_average: 5.9,
            adult: false,
            release_date: '2007-03-23',
            credit_id: '52fe42ecc3a36847f802d401',
        }, {
            id: 1771,
            character: 'Steve Rogers / Captain America',
            original_title: 'Captain America: The First Avenger',
            overview: "During World War II, Steve Rogers is a sickly man from Brooklyn who's transformed into super-soldier Captain America to aid in the war effort. Rogers must stop the Red Skull – Adolf Hitler's ruthless head of weaponry, and the leader of an organization that intends to use a mysterious device of untold powers for world domination.",
            vote_count: 13751,
            video: false,
            media_type: 'movie',
            poster_path: '/vSNxAJTlD0r02V9sPYpOjqDZXUK.jpg',
            backdrop_path: '/pmZtj1FKvQqISS6iQbkiLg5TAsr.jpg',
            popularity: 14.105,
            title: 'Captain America: The First Avenger',
            original_language: 'en',
            genre_ids: [
                28,
                12,
                878,
            ],
            vote_average: 6.9,
            adult: false,
            release_date: '2011-07-22',
            credit_id: '52fe4313c3a36847f8038851',
        }, {
            id: 7515,
            character: 'Syd',
            original_title: 'London',
            overview: 'London is a drug laden adventure that centers on a party in a New York loft where a young man is trying to win back his ex-girlfriend.',
            vote_count: 160,
            video: false,
            media_type: 'movie',
            poster_path: '/pnTRNDfdxdyx2tYKrTPlO3rcKk4.jpg',
            backdrop_path: '/qOu2ZH1beY391NPq9Xev09hg04Z.jpg',
            popularity: 8.868,
            title: 'London',
            original_language: 'en',
            genre_ids: [
                28,
                18,
                10749,
            ],
            vote_average: 6,
            adult: false,
            release_date: '2005-02-10',
            credit_id: '52fe4481c3a36847f809a31f',
        }, {
            id: 283350,
            department: 'Production',
            original_language: 'en',
            original_title: 'Before We Go',
            job: 'Producer',
            overview: 'A woman who is robbed on her way to catch the 1:30 train to Boston is left stranded in New York City. She meets a man who helps her during the course of the night and the two form a romance.',
            vote_count: 1070,
            video: false,
            media_type: 'movie',
            poster_path: '/b9YNJaIqkA2zoNdP4ORtpVMnmVo.jpg',
            backdrop_path: '/3OcSOfgO5Hcb1Vyy0zoomzJCwq3.jpg',
            title: 'Before We Go',
            popularity: 9.642,
            genre_ids: [
                35,
                18,
                10749,
            ],
            vote_average: 6.6,
            adult: false,
            release_date: '2014-09-11',
            credit_id: '554bb668c3a3685e4e0026ca',
        }, {
            id: 277547,
            department: 'Production',
            original_language: 'en',
            original_title: 'Playing It Cool',
            job: 'Executive Producer',
            overview: 'The story of a young man disillusioned by love who meets a breathtaking young woman at a charity dinner by pretending to be a philanthropist. Turns out that she’s engaged to a guy who doesn’t like her going on dates. Challenged by the chase, and egged on by his eclectic friends, he feigns a platonic relationship in order to keep seeing her as he tries to conquer her heart',
            vote_count: 450,
            video: false,
            media_type: 'movie',
            release_date: '2014-09-26',
            vote_average: 5.9,
            title: 'Playing It Cool',
            popularity: 12.871,
            genre_ids: [
                35,
                10749,
            ],
            backdrop_path: '/dDxwX9quYcQRaLb8Q5g3owrok9e.jpg',
            adult: false,
            poster_path: '/mBzSxaPOcq8XwXq4qkkyy8Ev9Go.jpg',
            credit_id: '554bb6dec3a3685e4c0029e3',
        }, {
            id: 87784,
            department: 'Production',
            original_language: 'en',
            episode_count: 1,
            job: 'Executive Producer',
            overview: 'The story of a father, Andy Barber, dealing with the accusation that his son, Jacob, is a 14-year-old murderer.',
            origin_country: [
                'US',
            ],
            original_name: 'Defending Jacob',
            genre_ids: [
                18,
            ],
            name: 'Defending Jacob',
            media_type: 'tv',
            first_air_date: '',
            backdrop_path: null,
            popularity: 1.4,
            vote_count: 0,
            vote_average: 0,
            poster_path: '/yTYlkKhIXocZH9YyigZoHeh4vKr.jpg',
            credit_id: '5c92fb3a9251412b5c778943',
        }],
    },
    invalid: {
        personIds: [
            'shdgv',
            'fghj',
        ],
    },
};

module.exports = testData;
